name: CI/CD

# 控制你的流程何時啟動
on:
  # 觸發條件設定為 pull "main" branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

  # 允許手動運行這個yml檔
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 檢查儲存庫，這樣才可以訪問
      - uses: actions/checkout@v3
          
    # 執行一組命令
    # Runs a set of commands using the runners shell
      - name: docker ProgreSQL start up
        run: |
          ls
          cat /etc/os-release
          cd Odoo14/20210603/docker-compose/odoo-db/ && sudo docker-compose up -d
          cd
          
      - name: python venv
        run: |
          cd python_venv/ && source odoo14_20210720/bin/activate
          sudo apt-get update
          sudo apt-get install libxml2-dev libxslt1-dev libssl-dev build-essential libsasl2-dev libffi-dev libldap2-dev python3.6-dev python-dev
          sudo apt-get install python3-setuptools
          sudo python3 -m pip install --upgrade pip 
          python3 -m pip install -r ../requirements.txt
          pip list
          cd
          
      - name: odoo server start up
        run: |
          cd Odoo14/20210603/odoo14/odoo && nohup python3 odoo-bin -w odoo -r odoo -c /home/runner/work/odoo-cicd-test/odoo-cicd-test/Odoo14/20210603/odoo14/odoo/config/odootest.conf &
          kill $(ps aux | grep '[p]ython3 odoo-bin' | awk '{print$2}')
          cd
                 
      - name: deploy to vm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            ls
            killall python3
            cd odoo-cicd-test
            git fetch
            git pull
            ls
            
            
      - name: deploy to vm
        timeout-minutes: 5
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/odoo-cicd-test/python_venv/ && source odoo14_20210720/bin/activate
            cd ~/odoo-cicd-test/Odoo14/20210603/odoo14/odoo && nohup python3 odoo-bin -w odoo -r odoo -c ~/odoo-cicd-test/Odoo14/20210603/odoo14/odoo/config/odoo.conf > nohup.out 2> nohup.err < /dev/null &

      
      # 執行單一命令
      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, test cd

      # 執行一組命令
      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
