name: CI/CD

# 控制你的流程何時啟動
on:
  # 觸發條件設定為 pull "main" branch
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ "main" ]

  # 允許手動運行這個yml檔
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 檢查儲存庫，這樣才可以訪問
      - uses: actions/checkout@v3
          
#     執行一組命令
#     Runs a set of commands using the runners shell
      - name: GitHub docker start up
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
        run: |
            docker-compose up -d
            
#       - name: GitHub odoo unit test
#         run: |
        
                 
      - name: GCP deploy to vm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop odoo-cicd-test_db_1 odoo-cicd-test_web_1
            cd odoo-cicd-test
            git fetch
            git pull
            docker-compose up -d
            
      
      # 執行單一命令
      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, test cd

      # 執行一組命令
      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
